### ISSUE TITLE
Write tests for nsconfig angular apps with sass and webpack

### ISSUE THREAD

**Issue by Natalia-Hristova** [NativeScript/nativescript-cli-tests#120]
Create angular app that has different nsconfig setup:

- with  `--bundle`
- without  `--bundle`

Test livesync changing:
- sass
- html
- ts

**Comment by dtopuzov** [comment]
https://github.com/NativeScript/nativescript-cli-tests/blob/master/tests/templates/starter_kit_templates_tests.py

**Comment by dtopuzov** [comment]
Implemented
