### ISSUE TITLE
Tns.run command blocks test execution without --justlaunch flag

### ISSUE THREAD

**Issue by Plamen5kov** [NativeScript/nativescript-cli-tests#27]
Test `test_003_calling_custom_generated_classes_declared_in_manifest` of `StaticBindingGenerator_Tests.py` blocks test execution when `Tns.run` command is used without `--justlaunch` flag.

```python
Tns.run_android(attributes={"--emulator": "",
                            "--path": self.app_name,
                            "--timeout": "120"})
```

Current used workaround is adding the `--justlaunch` flag to the `Tns.run` command, but we don't know why the main thread block happens.

**Comment by vchimev** [comment]
AFAIK, this is the default {N} CLI behavior - to release the console only if the `--justlaunch` option is specified. Isn't it, @Plamen5kov?

**Comment by Plamen5kov** [comment]
I didn't know that, if it's expected then there's no issue. I'm closing this.
